In [1]:
import pandas as pd
import re
import numpy as np
from sqlalchemy import create_engine
from matching_tools_new import *
from datetime import datetime
from dateutil.relativedelta import relativedelta
def c(series):
    if series is None: return 0
    if pd.api.types.is_numeric_dtype(series):
        return series.fillna(0)
    clean_series = series.astype(str).str.replace(',', '', regex=False).str.strip()
    return pd.to_numeric(clean_series, errors='coerce').fillna(0)
engine = create_engine('mysql+pymysql://arlo:!777ARLOarlo!?@localhost:3306/calculate_month')

In [2]:
# 获取当前日期
now = datetime.now()
# 计算上一个月
last_month = now - relativedelta(months=1)
last_month_str = last_month.strftime("%Y.%m")
# 得到核算当月的月份
cal_month = last_month.month

In [3]:
# 读取报表们
advertise_table = pd.read_excel(rf'Tik Tok\{last_month_str}\广告消耗.xlsx')
settlement_table = pd.read_excel(rf'Tik Tok\{last_month_str}\后台结算单.xlsx', sheet_name='Order details',dtype={'Order/adjustment ID': str,'SKU ID': str})
orders_table = pd.read_excel(rf'Tik Tok\{last_month_str}\领星订单.xlsx', sheet_name='sheet1',dtype={'ASIN/商品Id': str, '平台单号': str, '订单总金额': float, '订单出库成本(CNY)': float})

In [4]:
# 读取北美属性表与汇率
product_property = pd.read_sql('SELECT * FROM 属性表副本', con=engine)
product_property_us = product_property[product_property['国家']=='US']

In [5]:
exchange_ratio = {
    'USD_CNY':6.8701
}
weight_avg_price = 922 # tiktok加权单件，每月不同

### 首先根据Tik Tok的SKU与msku对应关系，为结算单表匹配MSKU

In [6]:
tiktok_sku_id = pd.read_csv(rf'Tik Tok\Tik Tok msku对应关系.csv',dtype={'SKU ID': str})
sku_map = tiktok_sku_id.set_index('SKU ID')['MSKU'].to_dict()
settlement_table['MSKU'] = settlement_table['SKU ID'].map(sku_map)

##### 没有匹配到，skuid为/的，是退款项，对应的MSKU需要在结算单非退款项的表中根据Order/adjustment ID与msku的映射去匹配

In [7]:
settlement_table_na = settlement_table[settlement_table['MSKU'].isna()]
settlement_table_na.to_csv(rf'Tik Tok\{last_month_str}\手动处理\结算单未匹配.csv',index=False)
settlement_table_na

,Statement date,Statement ID,Payment ID,Status,Currency,Type,Order/adjustment ID,SKU ID,Quantity,Product name,...,TikTok Shop shipping fee discount to customer,Mode of TikTok Shop shipping fee discount to customer,Return shipping fee (paid by customers).1,Estimated chargeable package weight,Chargeable package weight,FBT Chargeable goods weight,Collection methods,Delivery option,Signature confirmation service fee type,MSKU
25,2026/04/29,7633602756737107725,3473324603322765951,Paid,USD,Logistics reimbursement,7633602546125408014,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
198,2026/04/25,7632124839566198541,3473117699346305663,Paid,USD,Logistics reimbursement,7632194654725981965,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
920,2026/04/07,7625432356820469518,3472185763218625151,Paid,USD,Other adjustment,7625432174616381198,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1069,2026/04/04,7624335380318029581,3472050212882125439,Paid,USD,TikTok Shop reimbursement,7624436345746147085,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1134,2026/04/02,7623588413694773005,3471955294920348287,Paid,USD,Logistics reimbursement,7623588505561958157,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN

In [8]:
settlement_table = settlement_table[~settlement_table['Order/adjustment ID'].isin(settlement_table_na['Order/adjustment ID'])]
st_map = settlement_table.set_index('Order/adjustment ID')['MSKU'].to_dict()
refund_table = settlement_table_na[['Statement date','Currency','Type','Order/adjustment ID','Total settlement amount','Related order ID  ','MSKU']]
refund_table['MSKU'] = refund_table['Related order ID  '].map(st_map)
refund_table

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\2940262438.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refund_table['MSKU'] = refund_table['Related order ID  '].map(st_map)

,Statement date,Currency,Type,Order/adjustment ID,Total settlement amount,Related order ID,MSKU
25,2026/04/29,USD,Logistics reimbursement,7633602546125408014,138.70,577360065193808436,VSEX-HID1-ST
198,2026/04/25,USD,Logistics reimbursement,7632194654725981965,165.30,577354881017745635,VSE-ASH19
920,2026/04/07,USD,Other adjustment,7625432174616381198,-195.80,/\t,NaN
1069,2026/04/04,USD,TikTok Shop reimbursement,7624436345746147085,10.99,577297240230891734,332022
1134,2026/04/02,USD,Logistics reimbursement,7623588505561958157,93.74,577313147931627673,VSEX-CGM-BL

##### type为'Other adjustment'的订单，为活动费，需单独拎出来

In [ ]:
# 将Order/adjustment ID为'7602857461607876383'的MSKU设为'TN-24'，并排除Type为'Other adjustment'的行
# refund_table.loc[refund_table['Order/adjustment ID'] == '7620385655742973709', 'MSKU'] = '' # 手动补充了缺失的MSKU
refund_table = refund_table[refund_table['Type'] != 'Other adjustment']
refund_table

,Statement date,Currency,Type,Order/adjustment ID,Total settlement amount,Related order ID,MSKU
25,2026/04/29,USD,Logistics reimbursement,7633602546125408014,138.70,577360065193808436,VSEX-HID1-ST
198,2026/04/25,USD,Logistics reimbursement,7632194654725981965,165.30,577354881017745635,VSE-ASH19
1069,2026/04/04,USD,TikTok Shop reimbursement,7624436345746147085,10.99,577297240230891734,332022
1134,2026/04/02,USD,Logistics reimbursement,7623588505561958157,93.74,577313147931627673,VSEX-CGM-BL

#### 处理补发订单，部分订单为领星订单中，平台单号包含'bu'的订单，需要排除掉不发货单
- 补发订单中运单号为WO开头的走fba，需匹配fba fee，但是先要查出运单号对应的订单号
- 自建仓需要使用跟踪号匹配,运单号SNWE开头
- 乐歌仓使用订单号匹配就行，剩余运单号

In [10]:
reissue_orders = orders_table[orders_table['平台单号'].str.contains('bu') & (orders_table['状态'] != '不发货')]
reissue_orders = reissue_orders[['平台单号','ASIN/商品Id','SKU','数量','运单号','跟踪号','品名']]
reissue_orders

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名
1417,577322915763360212-bu2,NaN,20-020105-005,1,OBS006260330127,870100133500,311021-15x5J||15加仑棕色无纺布种植袋5pack
1576,577322915763360212-bu,NaN,20-020105-006,1,WO103683190115904513,AFTN2096259231,311021-10x5J||10加仑棕色无纺布种植袋5pack
1577,577323854909248233-bu,NaN,20-021305-013,1,OBS0062603260YX,889995153394,TN-55||TN-55||弹力爬藤网5*5FT(网格尺寸：10*10cm)
1614,577264284681212748-bu,NaN,20-050232-001,1,OBS0062603250Y0,889951192028,VSEX-HID1-ST||S4508B黄油机套装
1657,577262990140346687-bu,NaN,20-390301-003,1,OBS00626032410B,889909370481,VSEX-CGM-BL||糖果机套装
1687,577320267965567550-bu,NaN,20-021502-004,1,WO103682223146949632,AFTN2094765811,VSN-BASEAB8||BASEA&BKit8oz
1957,577308903595610531-bu,NaN,20-020304-003,1,OBS00626031612H,889631197637,SST-0001||12孔育苗盘6套装
2078,577306423985410128-bu,NaN,20-020601-011,1,WO103678563134410752,AFTN2063390711,VS-THB1S||蓝牙温湿度计+外置传感器
2113,576495597186225428-bu,NaN,20-040202-057,1,OBS0062603120YI,889531469367,VSV-AZS4E42A||AeroZeshS4塑料风机4寸+E42A控制器
2114,576494582826702123-bu,NaN,20-050232-001,1,WO103678195317541376,AFTN2075921031,VSEX-HID1-ST||S4508B黄油机套装
2140,576495452896138773-bu,NaN,20-020304-003,1,SNWE-260311-00103,UUS63B3190278044119,SST-0001||12孔育苗盘6套装
2171,576493481157040105-bu,NaN,20-020308-003,9,OBS0062603100ZI,889451074320,VS-CCB1||1.4lbCocoCoirBricks1-pack
2227,576491655916721806-bu,NaN,20-020304-003,3,SNWE-260309-00098,399411330551,SST-0001||12孔育苗盘6套装
2252,577302290780427223-bu,NaN,20-050232-001,1,OBS00626030812F,889395234785,VSEX-HID1-ST||S4508B黄油机套装
2319,576489397622248501-bu,NaN,20-380201-005,1,OBS006260306150,889350362988,VSI-VGDWC15||VGrowDWC水培套装4加仑
2335,577286386346660151-bu,NaN,20-340102-001,1,OBS00626030612K,889347372423,VSI-DIK01||滴灌套装（带A10插座）
2336,576488982957823390-bu1,NaN,20-020605-006,1,WO103676089379495936,9339589718061719755630,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）
2337,576488982957823390-bu1,NaN,20-020603-001,1,NaN,NaN,305131J||PH3和1土壤测试仪
2338,576488578676069472-bu,NaN,20-020605-006,1,WO103676087249285632,9339589684061731657824,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）
2339,576488578676069472-bu,NaN,20-020603-001,1,NaN,NaN,305131J||PH3和1土壤测试仪
2399,577169102575144987-bu,NaN,20-040202-167,1,OBS006260304145,889274549156,VSF-AWE6-G2||AeroWaveE6Gen2Black
2478,577303595994943940-bu,NaN,20-030102-011,1,OBS00626030213O,399190300367,332572J||绿色小水泵3000L
2571,577299058113483414-bu,NaN,20-050232-001,1,OBS0062602270XL,889126230957,VSEX-HID1-ST||S4508B黄油机套装
2601,577279721056473748-bu1,NaN,20-050232-001,1,OBS0062602260ZO,889088811493,VSEX-HID1-ST||S4508B黄油机套装
2702,577293474865779355-bu,NaN,20-050232-001,1,OBS006260222117,888967475130,VSEX-HID1-ST||S4508B黄油机套装
2736,577274586297045416-bu,NaN,20-010601-361,1,WO103671469690727424,AFTN2032606611,VSL-T52F-4||T5灯条2fit15Wx4bar
2871,577278307342716990-bu,NaN,20-040202-167,1,SNWE-260214-00163,398734177010,VSF-AWE6-G2||AeroWaveE6Gen2Black
2998,576477727404037622-bu,NaN,20-010609-021,1,OBS0062602090ZS,888593024616,VSS-UCS||SGSUSB分线器
3000,577279298413761485-bu,NaN,20-021012-071,1,WO103667229871562752,AFTN2015985671,GT-Pole||帐篷防缩杆

In [11]:
cols_to_fill = reissue_orders.columns[reissue_orders.isna().any()]
reissue_orders[cols_to_fill] = reissue_orders[cols_to_fill].ffill()
reissue_orders = reissue_orders.drop_duplicates()
reissue_orders = reissue_orders.reset_index(drop=True)
reissue_orders

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\792782590.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  reissue_orders[cols_to_fill] = reissue_orders[cols_to_fill].ffill()

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名
0,577322915763360212-bu2,NaN,20-020105-005,1,OBS006260330127,870100133500,311021-15x5J||15加仑棕色无纺布种植袋5pack
1,577322915763360212-bu,NaN,20-020105-006,1,WO103683190115904513,AFTN2096259231,311021-10x5J||10加仑棕色无纺布种植袋5pack
2,577323854909248233-bu,NaN,20-021305-013,1,OBS0062603260YX,889995153394,TN-55||TN-55||弹力爬藤网5*5FT(网格尺寸：10*10cm)
3,577264284681212748-bu,NaN,20-050232-001,1,OBS0062603250Y0,889951192028,VSEX-HID1-ST||S4508B黄油机套装
4,577262990140346687-bu,NaN,20-390301-003,1,OBS00626032410B,889909370481,VSEX-CGM-BL||糖果机套装
5,577320267965567550-bu,NaN,20-021502-004,1,WO103682223146949632,AFTN2094765811,VSN-BASEAB8||BASEA&BKit8oz
6,577308903595610531-bu,NaN,20-020304-003,1,OBS00626031612H,889631197637,SST-0001||12孔育苗盘6套装
7,577306423985410128-bu,NaN,20-020601-011,1,WO103678563134410752,AFTN2063390711,VS-THB1S||蓝牙温湿度计+外置传感器
8,576495597186225428-bu,NaN,20-040202-057,1,OBS0062603120YI,889531469367,VSV-AZS4E42A||AeroZeshS4塑料风机4寸+E42A控制器
9,576494582826702123-bu,NaN,20-050232-001,1,WO103678195317541376,AFTN2075921031,VSEX-HID1-ST||S4508B黄油机套装
10,576495452896138773-bu,NaN,20-020304-003,1,SNWE-260311-00103,UUS63B3190278044119,SST-0001||12孔育苗盘6套装
11,576493481157040105-bu,NaN,20-020308-003,9,OBS0062603100ZI,889451074320,VS-CCB1||1.4lbCocoCoirBricks1-pack
12,576491655916721806-bu,NaN,20-020304-003,3,SNWE-260309-00098,399411330551,SST-0001||12孔育苗盘6套装
13,577302290780427223-bu,NaN,20-050232-001,1,OBS00626030812F,889395234785,VSEX-HID1-ST||S4508B黄油机套装
14,576489397622248501-bu,NaN,20-380201-005,1,OBS006260306150,889350362988,VSI-VGDWC15||VGrowDWC水培套装4加仑
15,577286386346660151-bu,NaN,20-340102-001,1,OBS00626030612K,889347372423,VSI-DIK01||滴灌套装（带A10插座）
16,576488982957823390-bu1,NaN,20-020605-006,1,WO103676089379495936,9339589718061719755630,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）
17,576488982957823390-bu1,NaN,20-020603-001,1,WO103676089379495936,9339589718061719755630,305131J||PH3和1土壤测试仪
18,576488578676069472-bu,NaN,20-020605-006,1,WO103676087249285632,9339589684061731657824,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）
19,576488578676069472-bu,NaN,20-020603-001,1,WO103676087249285632,9339589684061731657824,305131J||PH3和1土壤测试仪
20,577169102575144987-bu,NaN,20-040202-167,1,OBS006260304145,889274549156,VSF-AWE6-G2||AeroWaveE6Gen2Black
21,577303595994943940-bu,NaN,20-030102-011,1,OBS00626030213O,399190300367,332572J||绿色小水泵3000L
22,577299058113483414-bu,NaN,20-050232-001,1,OBS0062602270XL,889126230957,VSEX-HID1-ST||S4508B黄油机套装
23,577279721056473748-bu1,NaN,20-050232-001,1,OBS0062602260ZO,889088811493,VSEX-HID1-ST||S4508B黄油机套装
24,577293474865779355-bu,NaN,20-050232-001,1,OBS006260222117,888967475130,VSEX-HID1-ST||S4508B黄油机套装
25,577274586297045416-bu,NaN,20-010601-361,1,WO103671469690727424,AFTN2032606611,VSL-T52F-4||T5灯条2fit15Wx4bar
26,577278307342716990-bu,NaN,20-040202-167,1,SNWE-260214-00163,398734177010,VSF-AWE6-G2||AeroWaveE6Gen2Black
27,576477727404037622-bu,NaN,20-010609-021,1,OBS0062602090ZS,888593024616,VSS-UCS||SGSUSB分线器
28,577279298413761485-bu,NaN,20-021012-071,1,WO103667229871562752,AFTN2015985671,GT-Pole||帐篷防缩杆

##### 补发订单的MSKU为品名列 || 前的内容

In [12]:
# 定义一个函数，智能提取 || 前的内容
def smart_extract(text):
    if not isinstance(text, str):
        return text
    # ^           : 从头开始
    # (.*?)       : 非贪婪匹配任意字符（这是我们要的结果）
    # [\|\|｜｜]+ : 匹配两个或以上的竖线类字符（兼容半角 | 和全角｜）
    # 注意：这里用了字符集来兼容多种竖线
    match = re.match(r'^(.*?)[\|\｜]{2,}', text)
    if match:
        return match.group(1)
    else:
        return text # 如果没有分隔符，返回原值

reissue_orders['MSKU'] = reissue_orders['品名'].apply(smart_extract)
reissue_orders['fba尾程'] = 0
reissue_orders

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名,MSKU,fba尾程
0,577322915763360212-bu2,NaN,20-020105-005,1,OBS006260330127,870100133500,311021-15x5J||15加仑棕色无纺布种植袋5pack,311021-15x5J,0
1,577322915763360212-bu,NaN,20-020105-006,1,WO103683190115904513,AFTN2096259231,311021-10x5J||10加仑棕色无纺布种植袋5pack,311021-10x5J,0
2,577323854909248233-bu,NaN,20-021305-013,1,OBS0062603260YX,889995153394,TN-55||TN-55||弹力爬藤网5*5FT(网格尺寸：10*10cm),TN-55,0
3,577264284681212748-bu,NaN,20-050232-001,1,OBS0062603250Y0,889951192028,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
4,577262990140346687-bu,NaN,20-390301-003,1,OBS00626032410B,889909370481,VSEX-CGM-BL||糖果机套装,VSEX-CGM-BL,0
5,577320267965567550-bu,NaN,20-021502-004,1,WO103682223146949632,AFTN2094765811,VSN-BASEAB8||BASEA&BKit8oz,VSN-BASEAB8,0
6,577308903595610531-bu,NaN,20-020304-003,1,OBS00626031612H,889631197637,SST-0001||12孔育苗盘6套装,SST-0001,0
7,577306423985410128-bu,NaN,20-020601-011,1,WO103678563134410752,AFTN2063390711,VS-THB1S||蓝牙温湿度计+外置传感器,VS-THB1S,0
8,576495597186225428-bu,NaN,20-040202-057,1,OBS0062603120YI,889531469367,VSV-AZS4E42A||AeroZeshS4塑料风机4寸+E42A控制器,VSV-AZS4E42A,0
9,576494582826702123-bu,NaN,20-050232-001,1,WO103678195317541376,AFTN2075921031,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
10,576495452896138773-bu,NaN,20-020304-003,1,SNWE-260311-00103,UUS63B3190278044119,SST-0001||12孔育苗盘6套装,SST-0001,0
11,576493481157040105-bu,NaN,20-020308-003,9,OBS0062603100ZI,889451074320,VS-CCB1||1.4lbCocoCoirBricks1-pack,VS-CCB1,0
12,576491655916721806-bu,NaN,20-020304-003,3,SNWE-260309-00098,399411330551,SST-0001||12孔育苗盘6套装,SST-0001,0
13,577302290780427223-bu,NaN,20-050232-001,1,OBS00626030812F,889395234785,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
14,576489397622248501-bu,NaN,20-380201-005,1,OBS006260306150,889350362988,VSI-VGDWC15||VGrowDWC水培套装4加仑,VSI-VGDWC15,0
15,577286386346660151-bu,NaN,20-340102-001,1,OBS00626030612K,889347372423,VSI-DIK01||滴灌套装（带A10插座）,VSI-DIK01,0
16,576488982957823390-bu1,NaN,20-020605-006,1,WO103676089379495936,9339589718061719755630,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）,305140-PEN,0
17,576488982957823390-bu1,NaN,20-020603-001,1,WO103676089379495936,9339589718061719755630,305131J||PH3和1土壤测试仪,305131J,0
18,576488578676069472-bu,NaN,20-020605-006,1,WO103676087249285632,9339589684061731657824,305140-PEN||测试笔组合（PH测试笔+水质笔设计款）,305140-PEN,0
19,576488578676069472-bu,NaN,20-020603-001,1,WO103676087249285632,9339589684061731657824,305131J||PH3和1土壤测试仪,305131J,0
20,577169102575144987-bu,NaN,20-040202-167,1,OBS006260304145,889274549156,VSF-AWE6-G2||AeroWaveE6Gen2Black,VSF-AWE6-G2,0
21,577303595994943940-bu,NaN,20-030102-011,1,OBS00626030213O,399190300367,332572J||绿色小水泵3000L,332572J,0
22,577299058113483414-bu,NaN,20-050232-001,1,OBS0062602270XL,889126230957,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
23,577279721056473748-bu1,NaN,20-050232-001,1,OBS0062602260ZO,889088811493,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
24,577293474865779355-bu,NaN,20-050232-001,1,OBS006260222117,888967475130,VSEX-HID1-ST||S4508B黄油机套装,VSEX-HID1-ST,0
25,577274586297045416-bu,NaN,20-010601-361,1,WO103671469690727424,AFTN2032606611,VSL-T52F-4||T5灯条2fit15Wx4bar,VSL-T52F-4,0
26,577278307342716990-bu,NaN,20-040202-167,1,SNWE-260214-00163,398734177010,VSF-AWE6-G2||AeroWaveE6Gen2Black,VSF-AWE6-G2,0
27,576477727404037622-bu,NaN,20-010609-021,1,OBS0062602090ZS,888593024616,VSS-UCS||SGSUSB分线器,VSS-UCS,0
28,577279298413761485-bu,NaN,20-021012-071,1,WO103667229871562752,AFTN2015985671,GT-Pole||帐篷防缩杆,GT-Pole,0

#### 将结算单和补发单整合在一起，保留计算所需的字段，后续直接用来匹配跟踪号，尾程费，体积，采购价等

In [13]:
settlement_table_final = settlement_table[['Order/adjustment ID','SKU ID','MSKU','Quantity','Total settlement amount']]
settlement_table_final['跟踪号'] = ''
reissue_orders_final = reissue_orders[['平台单号','ASIN/商品Id','MSKU','数量','跟踪号']]
reissue_orders_final['结算金额'] = 0
final_orders = pd.DataFrame(columns=['订单号', '商品id', 'MSKU', '数量', '结算金额', '跟踪号'])
final_orders['订单号'] = pd.concat([settlement_table_final['Order/adjustment ID'], reissue_orders_final['平台单号']])
final_orders['商品id'] = pd.concat([settlement_table_final['SKU ID'], reissue_orders_final['ASIN/商品Id']])
final_orders['MSKU'] = pd.concat([settlement_table_final['MSKU'], reissue_orders_final['MSKU']])
final_orders['数量'] = pd.concat([settlement_table_final['Quantity'], reissue_orders_final['数量']])
final_orders['结算金额'] = pd.concat([settlement_table_final['Total settlement amount'], reissue_orders_final['结算金额']])
final_orders['跟踪号'] = pd.concat([settlement_table_final['跟踪号'], reissue_orders_final['跟踪号']])

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\3208144708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  settlement_table_final['跟踪号'] = ''
C:\Users\admin\AppData\Local\Temp\ipykernel_5976\3208144708.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reissue_orders_final['结算金额'] = 0

##### 对领星订单表单元格取消合并，然后为订单号不包含bu的内容匹配跟踪号
- 订单表中是走FBA的订单需要匹配运单号，而非跟踪号

In [14]:
orders_table[['跟踪号','运单号']] = orders_table[['跟踪号','运单号']].ffill()
orders_table_fewer = orders_table[['平台单号','跟踪号','运单号']].drop_duplicates()
orders_table_fewer

                    平台单号                     跟踪号                   运单号
0     577370566869684487          AFTN2313790011  WO103696423220228096
1     577370552054157575  9234690391694713445229   1156244540898316551
2     577370503415828547  9200190391694775861294   1156244148248088643
3     577370503313592441          AFTN2317024381  WO103696423227827200
4     577370497150194391  9200190391694775860969   1156244134406230743
...                  ...                     ...                   ...
3021  577279298819822040  9200190391694722421786   1155709924992192984
3022  577279298413761485  9200190391694722421786   1155709924992192984
3023  577279298413761485  9234690391694708534174   1155709917932524493
3024  577279289802396274  9234690391694708534020   1155709887799530098
3025  577279217072575127  9234690391694708533054   1155709572082340503

[2721 rows x 3 columns]

In [15]:
mask_nobu = final_orders['订单号'].str.contains('bu') == False
orders_table_fewer_map = orders_table_fewer.set_index('平台单号')['跟踪号'].to_dict()
final_orders.loc[mask_nobu, '跟踪号'] = final_orders.loc[mask_nobu, '订单号'].map(orders_table_fewer_map)
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号
0,577369351340004030,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713380667
1,577369058052444798,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713376653
2,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,AFTN2260544841
3,577366986644688924,1732060687267893887,HGK1-36,1,60.40,AFTN2246325461
4,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061
...,...,...,...,...,...,...
24,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130
25,577274586297045416-bu,NaN,VSL-T52F-4,1,0.00,AFTN2032606611
26,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010
27,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616
28,577279298413761485-bu,NaN,GT-Pole,1,0.00,AFTN2015985671

In [16]:
# 对跟踪号为AFTN开头的订单，重新再匹配运单号
mask_AFTN = final_orders['跟踪号'].str.startswith('AFTN') == True
orders_table_fewer_map_new = orders_table_fewer.set_index('平台单号')['运单号'].to_dict()
final_orders.loc[mask_AFTN, '跟踪号'] = final_orders.loc[mask_AFTN, '订单号'].map(orders_table_fewer_map_new)
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号
0,577369351340004030,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713380667
1,577369058052444798,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713376653
2,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400
3,577366986644688924,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808
4,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061
...,...,...,...,...,...,...
24,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130
25,577274586297045416-bu,NaN,VSL-T52F-4,1,0.00,WO103671469690727424
26,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010
27,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616
28,577279298413761485-bu,NaN,GT-Pole,1,0.00,WO103667229871562752

##### 加载亚马逊translation报表、乐歌费用表、自建仓表

In [17]:
amz_translation1 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us.csv",skiprows=9)
amz_translation2 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us2.csv",skiprows=9)
lege = pd.read_excel(rf'Tik Tok\{last_month_str}\乐歌费用.xlsx')
self_storehouse = pd.read_excel(rf'Tik Tok\{last_month_str}\自建仓.xlsx',sheet_name='出库费用明细(outbound fee)')

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\2966350463.py:1: DtypeWarning: Columns (12,14,25,26,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  amz_translation1 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us.csv",skiprows=9)
C:\Users\admin\AppData\Local\Temp\ipykernel_5976\2966350463.py:2: DtypeWarning: Columns (12,14,25,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  amz_translation2 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us2.csv",skiprows=9)
d:\anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [18]:
final_orders_na = final_orders[final_orders['跟踪号'].isna()]
final_orders_na

Empty DataFrame
Columns: [订单号, 商品id, MSKU, 数量, 结算金额, 跟踪号]
Index: []

In [19]:
bu_amz = final_orders[final_orders['跟踪号'].str.startswith('WO', na=False)]

In [20]:
amz_orders = pd.read_excel(rf"Tik Tok\{last_month_str}\亚马逊发货订单.xlsx")
amz_orders_map = amz_orders.set_index('卖家订单号')['亚马逊订单号'].to_dict()
bu_amz['订单号'] = bu_amz['跟踪号'].map(amz_orders_map)
bu_amz

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\1406154769.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bu_amz['订单号'] = bu_amz['跟踪号'].map(amz_orders_map)

,订单号,商品id,MSKU,数量,结算金额,跟踪号
2,S01-1875880-3093214,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400
3,S01-4538859-9839642,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808
5,S01-6695490-5078868,1732003868204831359,PP-30-2,1,16.10,WO103694535470653952
16,S01-0205063-8430870,1731751761772974719,311001-1x5NJ,1,11.63,WO103693404136218624
24,S01-5594620-1842023,1731751761773302399,311001-10x5NJ,1,16.27,WO103694864229325824
...,...,...,...,...,...,...
5,NaN,NaN,VSN-BASEAB8,1,0.00,WO103682223146949632
7,NaN,NaN,VS-THB1S,1,0.00,WO103678563134410752
9,NaN,NaN,VSEX-HID1-ST,1,0.00,WO103678195317541376
25,NaN,NaN,VSL-T52F-4,1,0.00,WO103671469690727424
28,NaN,NaN,GT-Pole,1,0.00,WO103667229871562752

In [21]:
bu_amz_order_na = bu_amz[bu_amz['订单号'].isna()]
bu_amz_order_na

    订单号 商品id          MSKU 数量  结算金额                   跟踪号
1   NaN  NaN  311021-10x5J  1   0.0  WO103683190115904513
5   NaN  NaN   VSN-BASEAB8  1   0.0  WO103682223146949632
7   NaN  NaN      VS-THB1S  1   0.0  WO103678563134410752
9   NaN  NaN  VSEX-HID1-ST  1   0.0  WO103678195317541376
25  NaN  NaN    VSL-T52F-4  1   0.0  WO103671469690727424
28  NaN  NaN       GT-Pole  1   0.0  WO103667229871562752

In [22]:
# 缺失值补充
bu_amz.loc[bu_amz['跟踪号'] == 'WO103683190115904513', '订单号'] = 'S01-9276261-6012429'
bu_amz.loc[bu_amz['跟踪号'] == 'WO103682223146949632', '订单号'] = 'S01-2828766-3314047'
bu_amz.loc[bu_amz['跟踪号'] == 'WO103678563134410752', '订单号'] = 'S01-9947425-9178807'
bu_amz.loc[bu_amz['跟踪号'] == 'WO103678195317541376', '订单号'] = 'S01-9724087-2016420'
bu_amz.loc[bu_amz['跟踪号'] == 'WO103671469690727424', '订单号'] = 'S01-1331104-5903618'
bu_amz.loc[bu_amz['跟踪号'] == 'WO103667229871562752', '订单号'] = 'S01-2966769-2119600'

In [23]:
# 匹配fba fee
amz_translation = pd.concat([amz_translation1,amz_translation2],axis=0)
amz_translation_map = amz_translation.set_index('order id')['fba fees'].to_dict()
bu_amz['fba尾程'] = bu_amz['订单号'].map(amz_translation_map)
bu_amz

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\1316612532.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bu_amz['fba尾程'] = bu_amz['订单号'].map(amz_translation_map)

,订单号,商品id,MSKU,数量,结算金额,跟踪号,fba尾程
2,S01-1875880-3093214,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400,-13.43
3,S01-4538859-9839642,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808,-25.89
5,S01-6695490-5078868,1732003868204831359,PP-30-2,1,16.10,WO103694535470653952,-12.64
16,S01-0205063-8430870,1731751761772974719,311001-1x5NJ,1,11.63,WO103693404136218624,-12.36
24,S01-5594620-1842023,1731751761773302399,311001-10x5NJ,1,16.27,WO103694864229325824,-13.43
...,...,...,...,...,...,...,...
5,S01-2828766-3314047,NaN,VSN-BASEAB8,1,0.00,WO103682223146949632,-12.78
7,S01-9947425-9178807,NaN,VS-THB1S,1,0.00,WO103678563134410752,-11.81
9,S01-9724087-2016420,NaN,VSEX-HID1-ST,1,0.00,WO103678195317541376,-27.25
25,S01-1331104-5903618,NaN,VSL-T52F-4,1,0.00,WO103671469690727424,NaN
28,S01-2966769-2119600,NaN,GT-Pole,1,0.00,WO103667229871562752,NaN

In [24]:
bu_amz_map = bu_amz.set_index('跟踪号')['fba尾程'].to_dict()
final_orders['尾程'] = final_orders['跟踪号'].map(bu_amz_map).fillna(0)
# final_orders['fba尾程(CNY)'] = final_orders['fba尾程'].abs() * exchange_ratio['USD_CNY']
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
0,577369351340004030,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713380667,0
1,577369058052444798,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713376653,0
2,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400,-13.43
3,577366986644688924,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808,-25.89
4,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061,0
...,...,...,...,...,...,...,...
24,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130,0
25,577274586297045416-bu,NaN,VSL-T52F-4,1,0.00,WO103671469690727424,0
26,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010,0
27,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616,0
28,577279298413761485-bu,NaN,GT-Pole,1,0.00,WO103667229871562752,0

In [26]:
# 1月的订单drop掉单号为 577246913856966975-bu 的，因为这个订单的相关费用在2月被算过了
# reissue_orders = reissue_orders[~(reissue_orders['平台单号'] == '577246913856966975-bu')]
orders_to_remove = ['WO103671469690727424', 'WO103667229871562752'] # 2月的订单，去掉
final_orders = final_orders[~final_orders['跟踪号'].isin(orders_to_remove)]
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
0,577369351340004030,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713380667,0
1,577369058052444798,1731644032125211263,VSEX-HID1-ST,1,0.00,9234690391694713376653,0
2,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400,-13.43
3,577366986644688924,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808,-25.89
4,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061,0
...,...,...,...,...,...,...,...
22,577299058113483414-bu,NaN,VSEX-HID1-ST,1,0.00,889126230957,0
23,577279721056473748-bu1,NaN,VSEX-HID1-ST,1,0.00,889088811493,0
24,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130,0
26,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010,0
27,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616,0

#### 然后匹配乐歌和自建仓的尾程
- 处理乐歌和自建仓的尾程（补发和非补发的都在里面）
- 需要订单号+MSKU去匹配自建仓和乐歌里的平台号+MSKU对应的费用

##### 自建仓费用，有sku缺失的数据需要进行填充。填充的依据：
- 将平台单号进行排序，对于同平台单号下有sku缺失的记录，其sku列的值依照前一条记录填充。
- 出库费用小计列的空值，一律用0填充。
- 接着匹配结算单中的订单号，如果未匹配到，则不需要计算未匹配到的订单号的费用。

In [27]:
# 1. 确保按照平台单号排序，这是填充逻辑的基础
self_storehouse_fee = self_storehouse.sort_values(by='平台单号(platform No.)')
# 2. 核心：在单号组内进行“先看上面，再看下面”的双向填充 使用 transform 可以保持索引一致，直接更新原列
self_storehouse_fee['sku'] = self_storehouse_fee.groupby('平台单号(platform No.)')['sku'].transform(lambda x: x.ffill().bfill())
# 3. 出库费用小计列，空值填 0
self_storehouse_fee['出库费用小计（Subtotal）'] = self_storehouse_fee['出库费用小计（Subtotal）'].fillna(0)

In [28]:
lege_pivot = lege.pivot_table(index='跟踪号', values='包裹金额', aggfunc='sum').reset_index()
self_storehouse_fee_pivot = self_storehouse_fee.pivot_table(index='物流跟踪号（Tacking No.）', values='出库费用小计（Subtotal）', aggfunc='sum').reset_index()

In [29]:
endjourney_fee = pd.concat([lege_pivot[['跟踪号','包裹金额']].rename(columns={'包裹金额':'尾程'}), self_storehouse_fee_pivot[['物流跟踪号（Tacking No.）','出库费用小计（Subtotal）']].rename(columns={'物流跟踪号（Tacking No.）':'跟踪号','出库费用小计（Subtotal）':'尾程'})], axis=0)
endjourney_fee = endjourney_fee[endjourney_fee['跟踪号'].notnull()].drop_duplicates()
endjourney_fee

                       跟踪号     尾程
0             380022333548  16.68
1             380030346053  18.51
2             380048395340  16.56
3             380092954847  15.33
4             380097994338  18.06
...                    ...    ...
39348  UUS64T7750734765381   5.07
39349  UUS64U7750006309892   4.84
39350  UUS64U7750212099185   4.05
39351  UUS64U7750417888473   8.32
39352  UUS64U7750800520602   8.06

[39785 rows x 2 columns]

##### 匹配

In [30]:
mask_zero = final_orders['尾程'] == 0
endjourney_fee_map = (
    endjourney_fee
    .drop_duplicates()
    .set_index('跟踪号')['尾程']
)
final_orders.loc[mask_zero, '尾程'] = (
    final_orders.loc[mask_zero, '跟踪号']
    .map(endjourney_fee_map)
    .fillna(final_orders.loc[mask_zero, '尾程'])
)

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\1525771618.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(final_orders.loc[mask_zero, '尾程'])

##### 对于尾程依旧是0的，再用多渠道订单里的FBA费匹一下

In [35]:
multi_channel_order = pd.read_excel(rf'Tik Tok\{last_month_str}\多渠道订单.xlsx')
multi_map =  multi_channel_order.set_index('运单号')['FBA费'].to_dict()
mask_still_zero = final_orders['尾程'] == 0
final_orders.loc[mask_still_zero, '尾程'] = final_orders.loc[mask_still_zero, '跟踪号'].map(multi_map)
final_orders_fee_na = final_orders[final_orders['尾程'].isna()]
final_orders_fee_na

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
0,577369351340004030,1731644032125211263,VSEX-HID1-ST,1,0.0,9234690391694713380667,NaN
1,577369058052444798,1731644032125211263,VSEX-HID1-ST,1,0.0,9234690391694713376653,NaN

In [36]:
# final_orders中去掉final_orders_fee_na里的订单
final_orders = final_orders[~final_orders['订单号'].isin(final_orders_fee_na['订单号'])]
final_orders
# final_orders.to_csv('无尾程.csv', index=False, encoding='utf-8-sig')

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
2,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400,-13.43
3,577366986644688924,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808,-25.89
4,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061,-16.43
5,577365880219275537,1732003868204831359,PP-30-2,1,16.10,WO103694535470653952,-12.64
6,577365352862814448,1731751761773302399,311001-10x5NJ,2,33.37,9361289719963474325776,-16.17
...,...,...,...,...,...,...,...
22,577299058113483414-bu,NaN,VSEX-HID1-ST,1,0.00,889126230957,14.13
23,577279721056473748-bu1,NaN,VSEX-HID1-ST,1,0.00,889088811493,16.87
24,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130,14.13
26,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010,15.16
27,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616,14.01

##### 最后是广告费用，直接读取

In [37]:
advertise_info = pd.read_excel(rf'Tik Tok\{last_month_str}\广告消耗.xlsx')
advertise_info['花费人民币'] = advertise_info['花费（USD）']*exchange_ratio['USD_CNY']
advertise_info

            MSKU  花费（USD）        花费人民币
0   VSEX-HID1-ST  1308.93  8992.479993
1      VSE-ASH05   938.09  6444.772109
2    VSEX-CGM-BL   960.33  6597.563133
3     SST-2-0006   132.99   913.654599
4  Spray-SX-CS4J   157.46  1081.765946
5        332572J   292.42  2008.954642

##### 采购成本和头程成本的计算

In [38]:
# 为补发订单和结算单匹配采购价和体积
product_property_us_little = product_property_us[['MSKU','采购价(不含税)','单个产品体积(m³)']]
final_orders = final_orders.merge(product_property_us_little, on='MSKU', how='left')

In [39]:
final_orders_p_na = final_orders[final_orders[['采购价(不含税)','单个产品体积(m³)']].isna().any(axis=1)]
final_orders_p_na.to_csv(rf'Tik Tok\{last_month_str}\手动处理\MSKU相关信息缺失.csv',index=False)

In [40]:
final_orders['数量'] = pd.to_numeric(final_orders['数量'], errors='coerce')

In [41]:
final_orders['尾程'] = final_orders['尾程'].astype(float)
final_orders['尾程费用'] = final_orders['尾程'].abs() * exchange_ratio['USD_CNY']
final_orders['采购成本'] = final_orders['采购价(不含税)'] * final_orders['数量']
final_orders['头程成本'] = final_orders['单个产品体积(m³)'] * final_orders['数量'] * weight_avg_price
final_orders['结算金额(CNY)'] = final_orders['结算金额'] * exchange_ratio['USD_CNY']

In [42]:
# 尾程费用多余处理
final_orders.loc[final_orders.duplicated('跟踪号'), '尾程费用'] = 0
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程,采购价(不含税),单个产品体积(m³),尾程费用,采购成本,头程成本,结算金额(CNY)
0,577368109662769717,1731751761773302399,311001-10x5NJ,1,18.79,WO103695173646118400,-13.43,14.2313,0.004784,92.265443,14.2313,4.410848,129.089179
1,577366986644688924,1732060687267893887,HGK1-36,1,60.40,WO103694834953911808,-25.89,118.8350,0.027048,177.866889,118.8350,24.938256,414.954040
2,577366410649178190,1731751761773302399,311001-10x5NJ,2,33.37,TBA330605298061,-16.43,14.2313,0.004784,112.875743,28.4626,8.821696,229.255237
3,577365880219275537,1732003868204831359,PP-30-2,1,16.10,WO103694535470653952,-12.64,6.6372,0.004352,86.838064,6.6372,4.012544,110.608610
4,577365352862814448,1731751761773302399,311001-10x5NJ,2,33.37,9361289719963474325776,-16.17,14.2313,0.004784,111.089517,28.4626,8.821696,229.255237
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1212,577299058113483414-bu,NaN,VSEX-HID1-ST,1,0.00,889126230957,14.13,274.9204,0.026686,97.074513,274.9204,24.604492,0.000000
1213,577279721056473748-bu1,NaN,VSEX-HID1-ST,1,0.00,889088811493,16.87,274.9204,0.026686,115.898587,274.9204,24.604492,0.000000
1214,577293474865779355-bu,NaN,VSEX-HID1-ST,1,0.00,888967475130,14.13,274.9204,0.026686,97.074513,274.9204,24.604492,0.000000
1215,577278307342716990-bu,NaN,VSF-AWE6-G2,1,0.00,398734177010,15.16,76.3617,0.010944,104.150716,76.3617,10.090368,0.000000
1216,576477727404037622-bu,NaN,VSS-UCS,1,0.00,888593024616,14.01,8.5841,0.000260,96.250101,8.5841,0.239720,0.000000

In [43]:
# 最终透视
final_orders_pivot = final_orders.pivot_table(index='MSKU', values=['结算金额(CNY)', '采购成本', '头程成本', '尾程费用'], aggfunc='sum').reset_index()
final_orders_pivot

             MSKU        头程成本         尾程费用    结算金额(CNY)       采购成本
0       304113-21  122.430536    37.098540  1292.884119   424.7788
1       304113-22   65.175258    55.647810   245.193869   350.4426
2     304113-3018  105.476800   566.783250  1550.650271   438.9380
3       304113-32   60.962640   413.580020  1057.170988   297.3452
4       304113-33   68.239064     0.000000  1096.605362   366.3716
..            ...         ...          ...          ...        ...
128   VSN-BASEAB8    0.755118    87.799878     0.000000    29.8041
129       VSS-UCS    0.719160   114.112361    53.930285    25.7523
130  VSV-AZS4E42A   69.039360   114.936773  1864.613841  1091.4520
131      VSV-IFM4   20.177048   101.265274   261.063800   150.4424
132     VSV-IFP4C   51.049296  1387.485396  3034.729273   684.9558

[133 rows x 5 columns]

#### 绩效汇总表

In [44]:
# 计算退款
refund_table['平台退款费'] = refund_table['Total settlement amount'] * exchange_ratio['USD_CNY']
# 费用透视
refund_table_pivot = refund_table.pivot_table(index='MSKU', values='平台退款费', aggfunc='sum').reset_index()

C:\Users\admin\AppData\Local\Temp\ipykernel_5976\230112051.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refund_table['平台退款费'] = refund_table['Total settlement amount'] * exchange_ratio['USD_CNY']

In [45]:
#### 构建最终的Tik Tok绩效汇总表
tt_all = pd.concat([
    final_orders_pivot['MSKU'],
    advertise_info['MSKU'],
    refund_table_pivot['MSKU']
]).drop_duplicates().dropna().to_frame(name='MSKU')

In [46]:
# 结算单相关
final_orders_pivot_map1 = final_orders_pivot.set_index('MSKU')['结算金额(CNY)'].to_dict()
final_orders_pivot_map2 = final_orders_pivot.set_index('MSKU')['采购成本'].to_dict()
final_orders_pivot_map3 = final_orders_pivot.set_index('MSKU')['头程成本'].to_dict()
final_orders_pivot_map4 = final_orders_pivot.set_index('MSKU')['尾程费用'].to_dict()
# 广告费
advertise_info_map = advertise_info.set_index('MSKU')['花费人民币'].to_dict()
# 退款费
refund_table_pivot_map = refund_table_pivot.set_index('MSKU')['平台退款费'].to_dict()

In [47]:
# 都是USD
other_adjustment = 195.80 # 分摊活动费
storage_fee = 129.2616773296 # 分摊仓储费

In [48]:
tt_all['结算金额'] = tt_all['MSKU'].map(final_orders_pivot_map1).fillna(0)
tt_all['采购成本'] = tt_all['MSKU'].map(final_orders_pivot_map2).fillna(0)
tt_all['头程成本'] = tt_all['MSKU'].map(final_orders_pivot_map3).fillna(0)
tt_all['尾程费用'] = tt_all['MSKU'].map(final_orders_pivot_map4).fillna(0)
tt_all['广告费'] = tt_all['MSKU'].map(advertise_info_map).fillna(0)
# tt_all['平台退款费'] = 0
tt_all['平台退款费'] = tt_all['MSKU'].map(refund_table_pivot_map).fillna(0)
tt_all['结算金额占比'] = tt_all['结算金额'] / tt_all['结算金额'].sum()
tt_all['活动费分摊'] = other_adjustment * exchange_ratio['USD_CNY'] * tt_all['结算金额占比']
tt_all['仓储费分摊'] = storage_fee * exchange_ratio['USD_CNY'] * tt_all['结算金额占比']
tt_all['利润'] = tt_all['结算金额'] - tt_all['采购成本'] - tt_all['头程成本']  - tt_all['尾程费用'] - tt_all['广告费'] + tt_all['平台退款费'] - tt_all['活动费分摊'] - tt_all['仓储费分摊']

In [49]:
tt_all.to_excel(rf'Tik Tok\{last_month_str}\{cal_month}月Tik Tok绩效汇总表.xlsx', index=False)

##### 中间表输出

In [51]:
with pd.ExcelWriter(rf'Tik Tok\{last_month_str}\{cal_month}月中间表.xlsx') as writer:
    final_orders.to_excel(writer, sheet_name='结算单处理', index=False)
    refund_table.to_excel(writer, sheet_name='退款单处理', index=False)