In [1]:
import pandas as pd
import re
import numpy as np
from sqlalchemy import create_engine
from matching_tools_new import *
from datetime import datetime
from dateutil.relativedelta import relativedelta
def c(series):
    if series is None: return 0
    if pd.api.types.is_numeric_dtype(series):
        return series.fillna(0)
    clean_series = series.astype(str).str.replace(',', '', regex=False).str.strip()
    return pd.to_numeric(clean_series, errors='coerce').fillna(0)
engine = create_engine('mysql+pymysql://arlo:!777ARLOarlo!?@localhost:3306/calculate_month')

In [2]:
# 定义一个函数，智能提取 || 前的内容
def smart_extract(text):
    if not isinstance(text, str):
        return text
    # ^           : 从头开始
    # (.*?)       : 非贪婪匹配任意字符（这是我们要的结果）
    # [\|\|｜｜]+ : 匹配两个或以上的竖线类字符（兼容半角 | 和全角｜）
    # 注意：这里用了字符集来兼容多种竖线
    match = re.match(r'^(.*?)[\|\｜]{2,}', text)
    if match:
        return match.group(1)
    else:
        return text # 如果没有分隔符，返回原值

In [3]:
# 获取当前日期
now = datetime.now()
# 计算上一个月
last_month = now - relativedelta(months=1)
last_month_str = last_month.strftime("%Y.%m")
# 得到核算当月的月份
cal_month = last_month.month

In [4]:
# 读取报表们
advertise_table = pd.read_excel(rf'Tik Tok\{last_month_str}\广告消耗.xlsx')
settlement_table = pd.read_excel(rf'Tik Tok\{last_month_str}\后台结算单.xlsx', sheet_name='Order details',dtype={'Order/adjustment ID': str,'SKU ID': str})
orders_table = pd.read_excel(
    rf'Tik Tok\{last_month_str}\领星订单.xlsx', 
    sheet_name='sheet1',
    # 将 str 改为 'string'
    dtype={'ASIN/商品Id': 'string', '平台单号': 'string', '订单总金额': float, '订单出库成本(CNY)': float}
)
reissue_orders = pd.read_excel(rf'Tik Tok\{last_month_str}\补发订单.xlsx', sheet_name='sheet1',dtype={'ASIN/商品Id': str, '平台单号': str, '订单总金额': float, '订单出库成本(CNY)': float})

In [5]:
# 得到领星不发货订单
orders_table_cancelled = orders_table[orders_table['状态'] == '不发货']
orders_table_cancelled[['平台单号','MSKU','品名']] = orders_table_cancelled[['平台单号','MSKU','品名']].ffill()
mask_msku_na = orders_table_cancelled['MSKU'].isna()
orders_table_cancelled.loc[mask_msku_na, 'MSKU'] = orders_table_cancelled.loc[mask_msku_na, '品名'].apply(smart_extract)
orders_table_cancelled

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\984301403.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_table_cancelled[['平台单号','MSKU','品名']] = orders_table_cancelled[['平台单号','MSKU','品名']].ffill()

,系统单号,状态,店铺,站点,客服备注,标签,订购时间,发货时限,发货时间,标发时间,...,省/州,城市,区/县,邮编,门牌号,地址类型,公司名,地址行1,地址行2,地址行3
24,1.037065e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-05-31 07:54:13,2026-06-03 14:59:59,NaN,NaN,...,Georgia,Cusseta,NaN,31805,NaN,住宅地址,NaN,279 GA HIGHWAY 137,NaN,NaN
102,1.037057e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-05-29 00:53:20,2026-06-02 14:59:59,NaN,NaN,...,Oklahoma,Tulsa,NaN,74134,NaN,住宅地址,NaN,4705 S 129TH EAST AVE,NaN,NaN
143,1.037054e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-05-28 03:34:23,NaN,NaN,NaN,...,Alabama,Se****,NaN,36***,NaN,住宅地址,NaN,81** ****** ****** ***,NaN,NaN
174,1.037051e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,样品订单,2026-05-27 09:41:14,2026-05-28 14:59:59,NaN,NaN,...,Ohio,Akron,NaN,44312,NaN,NaN,NaN,233 Trent Dr,NaN,NaN
315,1.037039e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-05-23 23:05:06,2026-05-28 14:59:59,NaN,NaN,...,Illinois,Aurora,NaN,60503,NaN,住宅地址,NaN,2211 Keating Dr,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2007,1.036920e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,拆分订单,2026-04-19 04:41:45,2026-04-22 14:59:59,NaN,NaN,...,Texas,Hemphill,NaN,​,NaN,住宅地址,NaN,​,​,​
2019,1.036915e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-04-19 02:15:15,NaN,NaN,NaN,...,California,Eu****,NaN,​,NaN,住宅地址,NaN,​,​,​
2059,1.036912e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,拆分订单,2026-04-18 03:15:41,2026-04-22 14:59:59,NaN,NaN,...,Colorado,Colorado Spgs,NaN,​,NaN,住宅地址,NaN,​,​,​
2116,1.036907e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-04-16 18:12:43,NaN,NaN,NaN,...,Nevada,La* *****,NaN,​,NaN,住宅地址,NaN,​,​,​
2190,1.036901e+17,不发货,VIVOSUN-TTS-US,[TikTok].美国,NaN,NaN,2026-04-15 03:47:06,NaN,NaN,NaN,...,Washington,Bo*****,NaN,​,NaN,住宅地址,NaN,​,​,​

In [6]:
# 读取北美属性表与汇率
product_property = pd.read_sql('SELECT * FROM 属性表副本', con=engine)
product_property_us = product_property[product_property['国家']=='US']

In [7]:
exchange_ratio = {
    'USD_CNY':6.8420
}
weight_avg_price = 922 # tiktok加权单件，每月不同

### 首先根据Tik Tok的SKU与msku对应关系，为结算单表匹配MSKU

In [8]:
tiktok_sku_id = pd.read_csv(rf'Tik Tok\Tik Tok msku对应关系.csv',dtype={'SKU ID': str})
sku_map = tiktok_sku_id.set_index('SKU ID')['MSKU'].to_dict()
settlement_table['MSKU'] = settlement_table['SKU ID'].map(sku_map)

##### 退款项有2种
- 没有匹配到，skuid为/的，是退款项，对应的MSKU需要在结算单非退款项的表中根据Order/adjustment ID与msku的映射去匹配
- 结算单中Statement date和Order delivery date不在一个月且相差大于2天的

In [9]:
settlement_table_na = settlement_table[settlement_table['MSKU'].isna()]
settlement_table_na.to_csv(rf'Tik Tok\{last_month_str}\手动处理\结算单未匹配.csv',index=False)
settlement_table_na

,Statement date,Statement ID,Payment ID,Status,Currency,Type,Order/adjustment ID,SKU ID,Quantity,Product name,...,TikTok Shop shipping fee discount to customer,Mode of TikTok Shop shipping fee discount to customer,Return shipping fee (paid by customers).1,Estimated chargeable package weight,Chargeable package weight,FBT Chargeable goods weight,Collection methods,Delivery option,Signature confirmation service fee type,MSKU
103,2026/05/29,7644739083138352910,3474984408109257343,Paid,USD,Logistics reimbursement,7644752701689743118,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
173,2026/05/27,7643996831650744078,3474851242184249983,Paid,USD,Logistics reimbursement,7644010014772021005,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
174,2026/05/27,7643996831650744078,3474851242184249983,Paid,USD,Logistics reimbursement,7644009902743979789,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
298,2026/05/26,7643635001205196557,3474784301397938815,Paid,USD,Logistics reimbursement,7643634818119698189,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
418,2026/05/22,7642130684903802638,3474553315925267071,Paid,USD,Logistics reimbursement,7642142348085413645,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
781,2026/05/14,7639167629694256909,3474102618104500863,Paid,USD,Logistics reimbursement,7639199818289055502,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1052,2026/05/08,7636947430597592845,3473775918824854143,Paid,USD,Logistics reimbursement,7637220607903926030,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1054,2026/05/08,7636947430597592845,3473775918824854143,Paid,USD,Logistics reimbursement,7636978788991633166,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1055,2026/05/08,7636947430597592845,3473775918824854143,Paid,USD,Logistics reimbursement,7636947201826883342,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1109,2026/05/07,7636566700900484877,3473722843330941567,Paid,USD,Logistics reimbursement,7636592345735808781,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN
1323,2026/05/03,7635077747903186702,3473524125322154623,Paid,USD,Other adjustment,7635077534879713038,/,/,/,...,0,/,0,0.0,0.0,/,/,/,/,NaN

In [10]:
settlement_table = settlement_table[~settlement_table['Order/adjustment ID'].isin(settlement_table_na['Order/adjustment ID'])]
st_map = settlement_table.set_index('Order/adjustment ID')['MSKU'].to_dict()
refund_table1 = settlement_table_na[['Statement date','Currency','Type','Order/adjustment ID','Total settlement amount','Related order ID  ','MSKU']]
refund_table1['MSKU'] = refund_table1['Related order ID  '].map(st_map)
refund_table1

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\1812366524.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refund_table1['MSKU'] = refund_table1['Related order ID  '].map(st_map)

,Statement date,Currency,Type,Order/adjustment ID,Total settlement amount,Related order ID,MSKU
103,2026/05/29,USD,Logistics reimbursement,7644752701689743118,131.59,577387442459021710,VSEX-HID1-ST
173,2026/05/27,USD,Logistics reimbursement,7644010014772021005,19.35,577382430655091240,311001-2x5NJ
174,2026/05/27,USD,Logistics reimbursement,7644009902743979789,31.28,577390968051437746,COMBO-02NJ
298,2026/05/26,USD,Logistics reimbursement,7643634818119698189,68.92,577389565704573751,VSE-ASH05
418,2026/05/22,USD,Logistics reimbursement,7642142348085413645,124.29,577385779559633330,306201PVC-6J
781,2026/05/14,USD,Logistics reimbursement,7639199818289055502,123.97,577370170290967277,306201PVC-6J
1052,2026/05/08,USD,Logistics reimbursement,7637220607903926030,240.36,577354236341293921,NaN
1054,2026/05/08,USD,Logistics reimbursement,7636978788991633166,136.16,577365749095895747,VSEX-HID1-ST
1055,2026/05/08,USD,Logistics reimbursement,7636947201826883342,118.73,577366806314914226,306201PVC-6J
1109,2026/05/07,USD,Logistics reimbursement,7636592345735808781,32.78,577334629305127309,NaN
1323,2026/05/03,USD,Other adjustment,7635077534879713038,-220.57,/\t,NaN

In [11]:
settlement_table["Statement date"] = pd.to_datetime(settlement_table["Statement date"],errors="coerce")
settlement_table["Order delivery date"] = pd.to_datetime(settlement_table["Order delivery date"],errors="coerce")
refund_table2 = settlement_table[
    ( settlement_table['Statement date'].dt.month != settlement_table['Order delivery date'].dt.month
       )& ( (settlement_table['Statement date'] - settlement_table['Order delivery date']).dt.days.abs() > 2 )
]
refund_table2 = refund_table2[['Statement date','Currency','Type','Order/adjustment ID','Total settlement amount','Related order ID  ','MSKU']]
refund_table2

,Statement date,Currency,Type,Order/adjustment ID,Total settlement amount,Related order ID,MSKU
102,2026-05-30,USD,Order,577353559227470574,-18.86,577353559227470574,VSF-AWD4
295,2026-05-27,USD,Order,577350995883036726,-9.95,577350995883036726,332022
296,2026-05-27,USD,Order,577334450316349884,-1.01,577334450316349884,PS-007
297,2026-05-27,USD,Order,577327233640272501,-1.08,577327233640272501,311001-3x5NJ
627,2026-05-18,USD,Order,577334818914538138,-21.71,577334818914538138,311001-20x5NJ
736,2026-05-16,USD,Order,577341949801828405,-2.82,577341949801828405,VSE-ASH19
776,2026-05-15,USD,Order,577333313355485646,5.57,577333313355485646,Spray-SX-CS4J
777,2026-05-15,USD,Order,577333313355485646,-11.15,577333313355485646,Spray-SX-CS4J
823,2026-05-14,USD,Order,577341949801828405,-153.49,577341949801828405,VSE-ASH19
824,2026-05-14,USD,Order,577324276592513091,8.02,577324276592513091,VSE-ASH19
825,2026-05-14,USD,Order,577324276592513091,-16.05,577324276592513091,VSE-ASH19
855,2026-05-13,USD,Order,577360997262267063,1.41,577360997262267063,VSE-ASH05
856,2026-05-13,USD,Order,577360997262267063,-2.82,577360997262267063,VSE-ASH05
857,2026-05-13,USD,Order,577360997262267063,3.02,577360997262267063,VSE-ASH05
858,2026-05-13,USD,Order,577360997262267063,-6.03,577360997262267063,VSE-ASH05
927,2026-05-12,USD,Order,577362276292333681,1.41,577362276292333681,Spray-SX-CS4J
928,2026-05-12,USD,Order,577362276292333681,-2.82,577362276292333681,Spray-SX-CS4J
929,2026-05-12,USD,Order,577360997262267063,-48.41,577360997262267063,VSE-ASH05
994,2026-05-10,USD,Order,577333313355485646,-20.62,577333313355485646,Spray-SX-CS4J
1049,2026-05-09,USD,Order,577362276292333681,3.39,577362276292333681,Spray-SX-CS4J
1050,2026-05-09,USD,Order,577362276292333681,-6.78,577362276292333681,Spray-SX-CS4J
1051,2026-05-09,USD,Order,577362276292333681,-22.89,577362276292333681,Spray-SX-CS4J
1107,2026-05-08,USD,Order,577347087862305434,-21.20,577347087862305434,SPray-15L-GJ
1151,2026-05-07,USD,Order,577320725804257949,4.33,577320725804257949,VSL-T52F-8
1152,2026-05-07,USD,Order,577320725804257949,-5.41,577320725804257949,VSL-T52F-8
1153,2026-05-07,USD,Order,576489408561648930,-21.71,576489408561648930,311001-20x5NJ
1154,2026-05-07,USD,Order,577294229802684652,8.20,577294229802684652,VSEX-HID1-ST
1155,2026-05-07,USD,Order,577294229802684652,-10.25,577294229802684652,VSEX-HID1-ST
1471,2026-05-01,USD,Order,577360265195065949,-81.62,577360265195065949,304113-32

##### type为'Other adjustment'的订单，为活动费，需单独拎出来

In [12]:
# 将Order/adjustment ID为'7602857461607876383'的MSKU设为'TN-24'，并排除Type为'Other adjustment'的行
refund_table1.loc[refund_table1['Order/adjustment ID'] == '7637220607903926030', 'MSKU'] = 'VSI-VGDWC15' # 手动补充了缺失的MSKU
refund_table1.loc[refund_table1['Order/adjustment ID'] == '7636592345735808781', 'MSKU'] = '332572J'
refund_table = pd.concat([refund_table1,refund_table2],axis=0)
refund_table = refund_table[refund_table['Type'] != 'Other adjustment']
refund_table

,Statement date,Currency,Type,Order/adjustment ID,Total settlement amount,Related order ID,MSKU
103,2026/05/29,USD,Logistics reimbursement,7644752701689743118,131.59,577387442459021710,VSEX-HID1-ST
173,2026/05/27,USD,Logistics reimbursement,7644010014772021005,19.35,577382430655091240,311001-2x5NJ
174,2026/05/27,USD,Logistics reimbursement,7644009902743979789,31.28,577390968051437746,COMBO-02NJ
298,2026/05/26,USD,Logistics reimbursement,7643634818119698189,68.92,577389565704573751,VSE-ASH05
418,2026/05/22,USD,Logistics reimbursement,7642142348085413645,124.29,577385779559633330,306201PVC-6J
781,2026/05/14,USD,Logistics reimbursement,7639199818289055502,123.97,577370170290967277,306201PVC-6J
1052,2026/05/08,USD,Logistics reimbursement,7637220607903926030,240.36,577354236341293921,VSI-VGDWC15
1054,2026/05/08,USD,Logistics reimbursement,7636978788991633166,136.16,577365749095895747,VSEX-HID1-ST
1055,2026/05/08,USD,Logistics reimbursement,7636947201826883342,118.73,577366806314914226,306201PVC-6J
1109,2026/05/07,USD,Logistics reimbursement,7636592345735808781,32.78,577334629305127309,332572J
102,2026-05-30 00:00:00,USD,Order,577353559227470574,-18.86,577353559227470574,VSF-AWD4
295,2026-05-27 00:00:00,USD,Order,577350995883036726,-9.95,577350995883036726,332022
296,2026-05-27 00:00:00,USD,Order,577334450316349884,-1.01,577334450316349884,PS-007
297,2026-05-27 00:00:00,USD,Order,577327233640272501,-1.08,577327233640272501,311001-3x5NJ
627,2026-05-18 00:00:00,USD,Order,577334818914538138,-21.71,577334818914538138,311001-20x5NJ
736,2026-05-16 00:00:00,USD,Order,577341949801828405,-2.82,577341949801828405,VSE-ASH19
776,2026-05-15 00:00:00,USD,Order,577333313355485646,5.57,577333313355485646,Spray-SX-CS4J
777,2026-05-15 00:00:00,USD,Order,577333313355485646,-11.15,577333313355485646,Spray-SX-CS4J
823,2026-05-14 00:00:00,USD,Order,577341949801828405,-153.49,577341949801828405,VSE-ASH19
824,2026-05-14 00:00:00,USD,Order,577324276592513091,8.02,577324276592513091,VSE-ASH19
825,2026-05-14 00:00:00,USD,Order,577324276592513091,-16.05,577324276592513091,VSE-ASH19
855,2026-05-13 00:00:00,USD,Order,577360997262267063,1.41,577360997262267063,VSE-ASH05
856,2026-05-13 00:00:00,USD,Order,577360997262267063,-2.82,577360997262267063,VSE-ASH05
857,2026-05-13 00:00:00,USD,Order,577360997262267063,3.02,577360997262267063,VSE-ASH05
858,2026-05-13 00:00:00,USD,Order,577360997262267063,-6.03,577360997262267063,VSE-ASH05
927,2026-05-12 00:00:00,USD,Order,577362276292333681,1.41,577362276292333681,Spray-SX-CS4J
928,2026-05-12 00:00:00,USD,Order,577362276292333681,-2.82,577362276292333681,Spray-SX-CS4J
929,2026-05-12 00:00:00,USD,Order,577360997262267063,-48.41,577360997262267063,VSE-ASH05
994,2026-05-10 00:00:00,USD,Order,577333313355485646,-20.62,577333313355485646,Spray-SX-CS4J
1049,2026-05-09 00:00:00,USD,Order,577362276292333681,3.39,577362276292333681,Spray-SX-CS4J
1050,2026-05-09 00:00:00,USD,Order,577362276292333681,-6.78,577362276292333681,Spray-SX-CS4J
1051,2026-05-09 00:00:00,USD,Order,577362276292333681,-22.89,577362276292333681,Spray-SX-CS4J
1107,2026-05-08 00:00:00,USD,Order,577347087862305434,-21.20,577347087862305434,SPray-15L-GJ
1151,2026-05-07 00:00:00,USD,Order,577320725804257949,4.33,577320725804257949,VSL-T52F-8
1152,2026-05-07 00:00:00,USD,Order,577320725804257949,-5.41,577320725804257949,VSL-T52F-8
1153,2026-05-07 00:00:00,USD,Order,576489408561648930,-21.71,576489408561648930,311001-20x5NJ
1154,2026-05-07 00:00:00,USD,Order,577294229802684652,8.20,577294229802684652,VSEX-HID1-ST
1155,2026-05-07 00:00:00,USD,Order,577294229802684652,-10.25,577294229802684652,VSEX-HID1-ST
1471,2026-05-01 00:00:00,USD,Order,577360265195065949,-81.62,577360265195065949,304113-32

#### 处理补发订单，部分订单为领星订单中，平台单号包含'bu'的订单，需要排除掉不发货单
- 补发订单中运单号为WO开头的走fba，需匹配fba fee，但是先要查出运单号对应的订单号
- 自建仓需要使用跟踪号匹配,运单号SNWE开头
- 乐歌仓使用订单号匹配就行，剩余运单号

In [13]:
reissue_orders = reissue_orders[['平台单号','ASIN/商品Id','SKU','数量','运单号','跟踪号','品名']]
reissue_orders

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名
0,577391562207433041,NaN,20-310401-012,1,SNWE-260525-00205,381543525922,MGL-T5B2FWR4||MG T5 Linear Grow Lights Black 2...
1,577388021409419781,NaN,20-040704-032,1,OBS0062605210ZN,872065280652,VSE-ASH19||AeroStream 19L智能Wi-Fi加湿器（SGS，3核雾化片）
2,577392386079297665,NaN,20-040401-003,1,WO103701913427606528,1Z0F48X20335897336,"306143-0412J||VIVOSUN钢印滤芯 4"""
3,577392386079297665,NaN,20-040310-007,1,NaN,NaN,"306104-48J||铝箔管卡箍套装4""8ft"
4,577383339230597627,NaN,20-020103-003,1,WO103699429728472576,AFTN2440994761,311001-5x5NJ||5加仑黑色300g无纺布种植袋5个一包
5,577376223441686662,NaN,20-040310-008,1,WO103697663650008576,AFTN2371614581,"306104-4C||铝箔管卡箍套装4""25ft"

In [14]:
cols_to_fill = reissue_orders.columns[reissue_orders.isna().any()]
reissue_orders[cols_to_fill] = reissue_orders[cols_to_fill].ffill()
reissue_orders = reissue_orders.drop_duplicates()
reissue_orders = reissue_orders.reset_index(drop=True)
reissue_orders

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\792782590.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  reissue_orders[cols_to_fill] = reissue_orders[cols_to_fill].ffill()

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名
0,577391562207433041,NaN,20-310401-012,1,SNWE-260525-00205,381543525922,MGL-T5B2FWR4||MG T5 Linear Grow Lights Black 2...
1,577388021409419781,NaN,20-040704-032,1,OBS0062605210ZN,872065280652,VSE-ASH19||AeroStream 19L智能Wi-Fi加湿器（SGS，3核雾化片）
2,577392386079297665,NaN,20-040401-003,1,WO103701913427606528,1Z0F48X20335897336,"306143-0412J||VIVOSUN钢印滤芯 4"""
3,577392386079297665,NaN,20-040310-007,1,WO103701913427606528,1Z0F48X20335897336,"306104-48J||铝箔管卡箍套装4""8ft"
4,577383339230597627,NaN,20-020103-003,1,WO103699429728472576,AFTN2440994761,311001-5x5NJ||5加仑黑色300g无纺布种植袋5个一包
5,577376223441686662,NaN,20-040310-008,1,WO103697663650008576,AFTN2371614581,"306104-4C||铝箔管卡箍套装4""25ft"

##### 补发订单的MSKU为品名列 || 前的内容

In [15]:
reissue_orders['MSKU'] = reissue_orders['品名'].apply(smart_extract)
reissue_orders['fba尾程'] = 0
reissue_orders

,平台单号,ASIN/商品Id,SKU,数量,运单号,跟踪号,品名,MSKU,fba尾程
0,577391562207433041,NaN,20-310401-012,1,SNWE-260525-00205,381543525922,MGL-T5B2FWR4||MG T5 Linear Grow Lights Black 2...,MGL-T5B2FWR4,0
1,577388021409419781,NaN,20-040704-032,1,OBS0062605210ZN,872065280652,VSE-ASH19||AeroStream 19L智能Wi-Fi加湿器（SGS，3核雾化片）,VSE-ASH19,0
2,577392386079297665,NaN,20-040401-003,1,WO103701913427606528,1Z0F48X20335897336,"306143-0412J||VIVOSUN钢印滤芯 4""",306143-0412J,0
3,577392386079297665,NaN,20-040310-007,1,WO103701913427606528,1Z0F48X20335897336,"306104-48J||铝箔管卡箍套装4""8ft",306104-48J,0
4,577383339230597627,NaN,20-020103-003,1,WO103699429728472576,AFTN2440994761,311001-5x5NJ||5加仑黑色300g无纺布种植袋5个一包,311001-5x5NJ,0
5,577376223441686662,NaN,20-040310-008,1,WO103697663650008576,AFTN2371614581,"306104-4C||铝箔管卡箍套装4""25ft",306104-4C,0

#### 将结算单和补发单整合在一起，保留计算所需的字段，后续直接用来匹配跟踪号，尾程费，体积，采购价等

In [16]:
# 先排除掉settlement_table中包含refund_table的订单
settlement_table = settlement_table[~settlement_table['Order/adjustment ID'].isin(refund_table['Order/adjustment ID'])]
settlement_table_final = settlement_table[['Order/adjustment ID','SKU ID','MSKU','Quantity','Total settlement amount']]
settlement_table_final['跟踪号'] = ''
reissue_orders_final = reissue_orders[['平台单号','ASIN/商品Id','MSKU','数量','跟踪号']]
reissue_orders_final['结算金额'] = 0
final_orders = pd.DataFrame(columns=['订单号', '商品id', 'MSKU', '数量', '结算金额', '跟踪号'])
final_orders['订单号'] = pd.concat([settlement_table_final['Order/adjustment ID'], reissue_orders_final['平台单号']])
final_orders['商品id'] = pd.concat([settlement_table_final['SKU ID'], reissue_orders_final['ASIN/商品Id']])
final_orders['MSKU'] = pd.concat([settlement_table_final['MSKU'], reissue_orders_final['MSKU']])
final_orders['数量'] = pd.concat([settlement_table_final['Quantity'], reissue_orders_final['数量']])
final_orders['结算金额'] = pd.concat([settlement_table_final['Total settlement amount'], reissue_orders_final['结算金额']])
final_orders['跟踪号'] = pd.concat([settlement_table_final['跟踪号'], reissue_orders_final['跟踪号']])

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\4085777478.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  settlement_table_final['跟踪号'] = ''
C:\Users\admin\AppData\Local\Temp\ipykernel_18644\4085777478.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reissue_orders_final['结算金额'] = 0

##### 对领星订单表单元格取消合并，然后为订单号不包含bu的内容匹配跟踪号
- 订单表中是走FBA的订单需要匹配运单号，而非跟踪号

In [17]:
orders_table[['跟踪号','运单号']] = orders_table[['跟踪号','运单号']].ffill()
orders_table_fewer = orders_table[['平台单号','跟踪号','运单号']].drop_duplicates()
orders_table_fewer

                    平台单号                     跟踪号                   运单号
0     577413458244767834  9200190391694780656519   1156505603276771418
1     577413452070818026  9234690391694714996607   1156505586320511210
2     577413423056326988  9234690391694714996508   1156505425484616012
3     577413417894515272  9234690391694714996485   1156505392819573320
4     577413408021516986  9234690391694714996355   1156505329433612986
...                  ...                     ...                   ...
2192  577349040043233922          AFTN2136622191  WO103690219435356672
2193  577348970487649231  9200190391694771342230   1156115861516882895
2194  577348956509802819          AFTN2139003681  WO103690219452698624
2195  577348936464371723  9234690391694712501674   1156115628309450763
2196  577348928690688036          AFTN2139590351  WO103690219445896704

[2000 rows x 3 columns]

In [18]:
mask_nobu = final_orders['订单号'].str.contains('bu') == False
orders_table_fewer_map = orders_table_fewer.set_index('平台单号')['跟踪号'].to_dict()
final_orders.loc[mask_nobu, '跟踪号'] = final_orders.loc[mask_nobu, '订单号'].map(orders_table_fewer_map)
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号
0,577408517723885969,1732030169289429631,VSG-SPRAY-PP2L,1,16.32,9234690391694714866283
1,577408512269324689,1731751198544269951,VSGB-7,2,32.36,9234690391694714866245
2,577408390986830272,1731969165168841343,VSE-ASH09,1,64.61,9234690391694714861134
3,577407463495537471,1732063449615405695,VSEX-CGM-BL,1,-6.68,9234690391694714829530
4,577407388790657967,1731939821681873535,332572J,1,11.33,9234690391694714826881
...,...,...,...,...,...,...
1,577388021409419781,NaN,VSE-ASH19,1,0.00,9234690391694714080214
2,577392386079297665,NaN,306143-0412J,1,0.00,9234690391694714316368
3,577392386079297665,NaN,306104-48J,1,0.00,9234690391694714316368
4,577383339230597627,NaN,311001-5x5NJ,1,0.00,9234690391694713931784
5,577376223441686662,NaN,306104-4C,1,0.00,9234690391694713705071

In [19]:
# 对跟踪号为AFTN开头的订单，重新再匹配运单号
mask_AFTN = final_orders['跟踪号'].str.startswith('AFTN') == True
orders_table_fewer_map_new = orders_table_fewer.set_index('平台单号')['运单号'].to_dict()
final_orders.loc[mask_AFTN, '跟踪号'] = final_orders.loc[mask_AFTN, '订单号'].map(orders_table_fewer_map_new)
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号
0,577408517723885969,1732030169289429631,VSG-SPRAY-PP2L,1,16.32,9234690391694714866283
1,577408512269324689,1731751198544269951,VSGB-7,2,32.36,9234690391694714866245
2,577408390986830272,1731969165168841343,VSE-ASH09,1,64.61,9234690391694714861134
3,577407463495537471,1732063449615405695,VSEX-CGM-BL,1,-6.68,9234690391694714829530
4,577407388790657967,1731939821681873535,332572J,1,11.33,9234690391694714826881
...,...,...,...,...,...,...
1,577388021409419781,NaN,VSE-ASH19,1,0.00,9234690391694714080214
2,577392386079297665,NaN,306143-0412J,1,0.00,9234690391694714316368
3,577392386079297665,NaN,306104-48J,1,0.00,9234690391694714316368
4,577383339230597627,NaN,311001-5x5NJ,1,0.00,9234690391694713931784
5,577376223441686662,NaN,306104-4C,1,0.00,9234690391694713705071

##### 加载亚马逊translation报表、乐歌费用表、自建仓表

In [20]:
amz_translation1 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us.csv",skiprows=9)
amz_translation2 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us2.csv",skiprows=9)
lege = pd.read_excel(rf'Tik Tok\{last_month_str}\乐歌费用.xlsx')
self_storehouse = pd.read_excel(rf'Tik Tok\{last_month_str}\自建仓.xlsx',sheet_name='出库费用明细(outbound fee)')

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\2966350463.py:1: DtypeWarning: Columns (14,25,26,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  amz_translation1 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us.csv",skiprows=9)
C:\Users\admin\AppData\Local\Temp\ipykernel_18644\2966350463.py:2: DtypeWarning: Columns (12,14,25,26,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  amz_translation2 = pd.read_csv(rf"Tik Tok\{last_month_str}\amz_transaction_us2.csv",skiprows=9)
d:\anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\anaconda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [21]:
final_orders_na = final_orders[final_orders['跟踪号'].isna()]
final_orders_na

                     订单号                 商品id        MSKU 数量   结算金额  跟踪号
1149  577329712658288981  1732023713252283007  SPray-80LJ  1  -8.93  NaN
1150  577329712658288981  1732023713252283007  SPray-80LJ  1  33.00  NaN

In [22]:
# 手动补充跟踪号
final_orders.loc[final_orders['订单号'] == '577329712658288981', '跟踪号'] = '9234690391694711673167'

In [23]:
bu_amz = final_orders[final_orders['跟踪号'].str.startswith('WO', na=False)]

In [24]:
amz_orders = pd.read_excel(rf"Tik Tok\{last_month_str}\亚马逊发货订单.xlsx")
amz_orders_map = amz_orders.set_index('卖家订单号')['亚马逊订单号'].to_dict()
bu_amz['订单号'] = bu_amz['跟踪号'].map(amz_orders_map)
bu_amz

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\1406154769.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bu_amz['订单号'] = bu_amz['跟踪号'].map(amz_orders_map)

,订单号,商品id,MSKU,数量,结算金额,跟踪号
64,S01-1251218-4766021,1732030316430529151,HDR004,1,21.47,WO103705449198317568
65,S01-7115548-9011664,1731984818503258751,NB-002J,1,15.21,WO103705437000428032
66,S01-3331477-7667609,1731682306923860607,PS-006,1,14.31,WO103705436604029952
70,S01-6992078-4317263,1731984818503258751,NB-002J,1,15.21,WO103705086527024128
105,S01-0122354-4116461,1731708188813922943,304113-21,1,57.04,WO103704730068753408
...,...,...,...,...,...,...
1320,S01-2286660-6425233,1732060526473482879,332576J,1,0.00,WO103696579772370944
1394,S01-3202970-3022818,1731708188814054015,304113-3018,1,62.64,WO103695723871300096
1446,S01-5229444-0115662,1731751761773302399,311001-10x5NJ,1,18.79,WO103695532905681408
1447,S01-4354402-2750867,1731640237210047103,VSV-IFM4,1,37.58,WO103695532895673344
1448,S01-4291763-8411608,1732003868204831359,PP-30-2,1,16.10,WO103695247928003072

In [25]:
bu_amz_order_na = bu_amz[bu_amz['订单号'].isna()]
bu_amz_order_na

Empty DataFrame
Columns: [订单号, 商品id, MSKU, 数量, 结算金额, 跟踪号]
Index: []

In [ ]:
# 缺失值补充
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103683190115904513', '订单号'] = 'S01-9276261-6012429'
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103682223146949632', '订单号'] = 'S01-2828766-3314047'
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103678563134410752', '订单号'] = 'S01-9947425-9178807'
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103678195317541376', '订单号'] = 'S01-9724087-2016420'
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103671469690727424', '订单号'] = 'S01-1331104-5903618'
# bu_amz.loc[bu_amz['跟踪号'] == 'WO103667229871562752', '订单号'] = 'S01-2966769-2119600'

In [26]:
# 匹配fba fee
amz_translation = pd.concat([amz_translation1,amz_translation2],axis=0)
amz_translation['fba fees'] = c(amz_translation['fba fees'])
amz_translation_groupby = amz_translation.groupby('order id')['fba fees'].sum().reset_index()
amz_translation_map = amz_translation_groupby.set_index('order id')['fba fees'].to_dict()
bu_amz['fba尾程'] = bu_amz['订单号'].map(amz_translation_map)
bu_amz

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\2863958401.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bu_amz['fba尾程'] = bu_amz['订单号'].map(amz_translation_map)

,订单号,商品id,MSKU,数量,结算金额,跟踪号,fba尾程
64,S01-1251218-4766021,1732030316430529151,HDR004,1,21.47,WO103705449198317568,-13.12
65,S01-7115548-9011664,1731984818503258751,NB-002J,1,15.21,WO103705437000428032,-13.12
66,S01-3331477-7667609,1731682306923860607,PS-006,1,14.31,WO103705436604029952,-11.61
70,S01-6992078-4317263,1731984818503258751,NB-002J,1,15.21,WO103705086527024128,-13.22
105,S01-0122354-4116461,1731708188813922943,304113-21,1,57.04,WO103704730068753408,-27.63
...,...,...,...,...,...,...,...
1320,S01-2286660-6425233,1732060526473482879,332576J,1,0.00,WO103696579772370944,-11.61
1394,S01-3202970-3022818,1731708188814054015,304113-3018,1,62.64,WO103695723871300096,-26.60
1446,S01-5229444-0115662,1731751761773302399,311001-10x5NJ,1,18.79,WO103695532905681408,-13.43
1447,S01-4354402-2750867,1731640237210047103,VSV-IFM4,1,37.58,WO103695532895673344,-14.74
1448,S01-4291763-8411608,1732003868204831359,PP-30-2,1,16.10,WO103695247928003072,-12.78

In [27]:
bu_amz_map = bu_amz.set_index('跟踪号')['fba尾程'].to_dict()
final_orders['尾程'] = final_orders['跟踪号'].map(bu_amz_map).fillna(0)
# final_orders['fba尾程(CNY)'] = final_orders['fba尾程'].abs() * exchange_ratio['USD_CNY']
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
0,577408517723885969,1732030169289429631,VSG-SPRAY-PP2L,1,16.32,9234690391694714866283,0.0
1,577408512269324689,1731751198544269951,VSGB-7,2,32.36,9234690391694714866245,0.0
2,577408390986830272,1731969165168841343,VSE-ASH09,1,64.61,9234690391694714861134,0.0
3,577407463495537471,1732063449615405695,VSEX-CGM-BL,1,-6.68,9234690391694714829530,0.0
4,577407388790657967,1731939821681873535,332572J,1,11.33,9234690391694714826881,0.0
...,...,...,...,...,...,...,...
1,577388021409419781,NaN,VSE-ASH19,1,0.00,9234690391694714080214,0.0
2,577392386079297665,NaN,306143-0412J,1,0.00,9234690391694714316368,0.0
3,577392386079297665,NaN,306104-48J,1,0.00,9234690391694714316368,0.0
4,577383339230597627,NaN,311001-5x5NJ,1,0.00,9234690391694713931784,0.0
5,577376223441686662,NaN,306104-4C,1,0.00,9234690391694713705071,0.0

In [ ]:
# 1月的订单drop掉单号为 577246913856966975-bu 的，因为这个订单的相关费用在2月被算过了
# reissue_orders = reissue_orders[~(reissue_orders['平台单号'] == '577246913856966975-bu')]
# orders_to_remove = ['WO103671469690727424', 'WO103667229871562752'] # 2月的订单，去掉
final_orders = final_orders[~final_orders['跟踪号'].isin(orders_to_remove)]
final_orders

#### 然后匹配乐歌和自建仓的尾程
- 处理乐歌和自建仓的尾程（补发和非补发的都在里面）
- 需要订单号+MSKU去匹配自建仓和乐歌里的平台号+MSKU对应的费用

##### 自建仓费用，有sku缺失的数据需要进行填充。填充的依据：
- 将平台单号进行排序，对于同平台单号下有sku缺失的记录，其sku列的值依照前一条记录填充。
- 出库费用小计列的空值，一律用0填充。
- 接着匹配结算单中的订单号，如果未匹配到，则不需要计算未匹配到的订单号的费用。

In [28]:
# 1. 确保按照平台单号排序，这是填充逻辑的基础
self_storehouse_fee = self_storehouse.sort_values(by='平台单号(platform No.)')
# 2. 核心：在单号组内进行“先看上面，再看下面”的双向填充 使用 transform 可以保持索引一致，直接更新原列
self_storehouse_fee['sku'] = self_storehouse_fee.groupby('平台单号(platform No.)')['sku'].transform(lambda x: x.ffill().bfill())
# 3. 出库费用小计列，空值填 0
self_storehouse_fee['出库费用小计（Subtotal）'] = self_storehouse_fee['出库费用小计（Subtotal）'].fillna(0)

In [29]:
lege_pivot = lege.pivot_table(index='跟踪号', values='包裹金额', aggfunc='sum').reset_index()
self_storehouse_fee_pivot = self_storehouse_fee.pivot_table(index='物流跟踪号（Tacking No.）', values='出库费用小计（Subtotal）', aggfunc='sum').reset_index()

In [30]:
endjourney_fee = pd.concat([lege_pivot[['跟踪号','包裹金额']].rename(columns={'包裹金额':'尾程'}), self_storehouse_fee_pivot[['物流跟踪号（Tacking No.）','出库费用小计（Subtotal）']].rename(columns={'物流跟踪号（Tacking No.）':'跟踪号','出库费用小计（Subtotal）':'尾程'})], axis=0)
endjourney_fee = endjourney_fee[endjourney_fee['跟踪号'].notnull()].drop_duplicates()
endjourney_fee

                       跟踪号     尾程
0             380614314481  10.76
1             380626221304  11.91
2             380629244966  20.90
3             380815701999  19.50
4             380850284880  10.22
...                    ...    ...
18235  UUS65U7750202883122   6.05
18236  UUS65U7750224297707   5.82
18237  UUS65U7750692175832   4.73
18238  UUS65U7750713590414   4.07
18239  UUS65V7750100353718  13.09

[18772 rows x 2 columns]

##### 匹配

In [31]:
mask_zero = final_orders['尾程'] == 0
endjourney_fee_map = (
    endjourney_fee
    .drop_duplicates()
    .set_index('跟踪号')['尾程']
)
final_orders.loc[mask_zero, '尾程'] = (
    final_orders.loc[mask_zero, '跟踪号']
    .map(endjourney_fee_map)
    .fillna(final_orders.loc[mask_zero, '尾程'])
)

In [32]:
# 手动补充缺失运费
final_orders.loc[final_orders['跟踪号'] == '9361289722664464243677', '尾程'] = -16.75
final_orders.loc[final_orders['跟踪号'] == 'TBA331201712251', '尾程'] = 0
final_orders.loc[final_orders['跟踪号'] == '9361289675064162545357', '尾程'] = -11.8
final_orders.loc[final_orders['跟踪号'] == 'TBA330562667386', '尾程'] = -6.5600000000000005
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程
0,577408517723885969,1732030169289429631,VSG-SPRAY-PP2L,1,16.32,9234690391694714866283,1.000
1,577408512269324689,1731751198544269951,VSGB-7,2,32.36,9234690391694714866245,3.725
2,577408390986830272,1731969165168841343,VSE-ASH09,1,64.61,9234690391694714861134,2.000
3,577407463495537471,1732063449615405695,VSEX-CGM-BL,1,-6.68,9234690391694714829530,1.000
4,577407388790657967,1731939821681873535,332572J,1,11.33,9234690391694714826881,1.400
...,...,...,...,...,...,...,...
1,577388021409419781,NaN,VSE-ASH19,1,0.00,9234690391694714080214,2.700
2,577392386079297665,NaN,306143-0412J,1,0.00,9234690391694714316368,1.200
3,577392386079297665,NaN,306104-48J,1,0.00,9234690391694714316368,1.200
4,577383339230597627,NaN,311001-5x5NJ,1,0.00,9234690391694713931784,1.600
5,577376223441686662,NaN,306104-4C,1,0.00,9234690391694713705071,1.000

##### 最后是广告费用，直接读取

In [33]:
advertise_info = pd.read_excel(rf'Tik Tok\{last_month_str}\广告消耗.xlsx')
advertise_info['花费人民币'] = advertise_info['花费（USD）']*exchange_ratio['USD_CNY']
advertise_info

            MSKU  花费（USD）        花费人民币
0   VSEX-HID1-ST  1960.90  13416.47780
1      VSE-ASH05  1048.61   7174.58962
2    VSEX-CGM-BL   706.34   4832.77828
3  Spray-SX-CS4J   402.52   2754.04184
4        332572J   436.50   2986.53300

##### 采购成本和头程成本的计算

In [34]:
# 为补发订单和结算单匹配采购价和体积
product_property_us_little = product_property_us[['MSKU','采购价(不含税)','单个产品体积(m³)']]
final_orders = final_orders.merge(product_property_us_little, on='MSKU', how='left')

In [35]:
final_orders_p_na = final_orders[final_orders[['采购价(不含税)','单个产品体积(m³)']].isna().any(axis=1)]
final_orders_p_na.to_csv(rf'Tik Tok\{last_month_str}\手动处理\MSKU相关信息缺失.csv',index=False)

In [36]:
final_orders['数量'] = pd.to_numeric(final_orders['数量'], errors='coerce')

In [37]:
final_orders['尾程'] = final_orders['尾程'].astype(float)
final_orders['尾程费用'] = final_orders['尾程'].abs() * exchange_ratio['USD_CNY']
final_orders['采购成本'] = final_orders['采购价(不含税)'] * final_orders['数量']
final_orders['头程成本'] = final_orders['单个产品体积(m³)'] * final_orders['数量'] * weight_avg_price
final_orders['结算金额(CNY)'] = final_orders['结算金额'] * exchange_ratio['USD_CNY']

In [38]:
# 尾程费用多余处理
final_orders.loc[final_orders.duplicated('跟踪号'), '尾程费用'] = 0
final_orders

,订单号,商品id,MSKU,数量,结算金额,跟踪号,尾程,采购价(不含税),单个产品体积(m³),尾程费用,采购成本,头程成本,结算金额(CNY)
0,577408517723885969,1732030169289429631,VSG-SPRAY-PP2L,1,16.32,9234690391694714866283,1.000,12.2934,0.010353,6.84200,12.2934,9.545466,111.66144
1,577408512269324689,1731751198544269951,VSGB-7,2,32.36,9234690391694714866245,3.725,19.5144,0.003915,25.48645,39.0288,7.219260,221.40712
2,577408390986830272,1731969165168841343,VSE-ASH09,1,64.61,9234690391694714861134,2.000,213.7876,0.030800,13.68400,213.7876,28.397600,442.06162
3,577407463495537471,1732063449615405695,VSEX-CGM-BL,1,-6.68,9234690391694714829530,1.000,169.0620,0.005853,6.84200,169.0620,5.396466,-45.70456
4,577407388790657967,1731939821681873535,332572J,1,11.33,9234690391694714826881,1.400,27.6106,0.002736,9.57880,27.6106,2.522592,77.51986
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433,577388021409419781,NaN,VSE-ASH19,1,0.00,9234690391694714080214,2.700,353.1681,0.080104,0.00000,353.1681,73.855888,0.00000
1434,577392386079297665,NaN,306143-0412J,1,0.00,9234690391694714316368,1.200,57.0266,0.015015,0.00000,57.0266,13.843830,0.00000
1435,577392386079297665,NaN,306104-48J,1,0.00,9234690391694714316368,1.200,8.2215,0.002288,0.00000,8.2215,2.109536,0.00000
1436,577383339230597627,NaN,311001-5x5NJ,1,0.00,9234690391694713931784,1.600,10.8782,0.003003,0.00000,10.8782,2.768766,0.00000
1437,577376223441686662,NaN,306104-4C,1,0.00,9234690391694713705071,1.000,15.2745,0.004968,0.00000,15.2745,4.580496,0.00000

##### 判断取消订单，将其头程尾程采购价置0

In [39]:
# 1. 处理 orders_table，生成拼接列并输出不发货 DataFrame
orders_table_cancelled['平台单号_MSKU'] = (
    orders_table_cancelled['平台单号'].astype(str).str.strip() + '_' + 
    orders_table_cancelled['MSKU'].astype(str).str.strip().str.upper()
)
# 提取状态为“不发货”的唯一标识集合（用于后面快速匹配）
cancelled_platform_ids = set(orders_table_cancelled['平台单号_MSKU'])
cancelled_output_df = orders_table_cancelled[['平台单号','MSKU', '平台单号_MSKU']].copy()
# 2. 处理 final_orders，生成拼接列并执行匹配置 0 逻辑
# 在 final_orders 中生成对应的【订单号_MSKU】新列（同样去空格、转大写，确保标准对齐）
final_orders['订单号_MSKU'] = [
    f"{str(oid).strip()}_{str(msku).strip().upper()}"
    for oid, msku in zip(final_orders['订单号'], final_orders['MSKU'])
]
# 根据新生成的列进行匹配，添加“取消订单”备注
final_orders['备注'] = final_orders['订单号_MSKU'].apply(
    lambda x: '取消订单' if x in cancelled_platform_ids else ''
)
# 将标记为取消订单的成本列置 0
cost_columns = ['采购成本', '头程成本', '尾程费用']
final_orders.loc[final_orders['备注'] == '取消订单', cost_columns] = 0

C:\Users\admin\AppData\Local\Temp\ipykernel_18644\1392347468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_table_cancelled['平台单号_MSKU'] = (

In [40]:
# 最终透视
final_orders_pivot = final_orders.pivot_table(index='MSKU', values=['结算金额(CNY)', '采购成本', '头程成本', '尾程费用'], aggfunc='sum').reset_index()
final_orders_pivot

             MSKU        头程成本       尾程费用   结算金额(CNY)      采购成本
0       304113-21  275.468706  515.33944  2323.95372  955.7523
1       304113-22   65.175258  202.38636   840.47128  350.4426
2       304113-27  179.861916  642.05328  1632.98014  976.9914
3     304113-3018   79.107600  530.32342  1257.01224  315.9291
4       304113-32   30.481320  204.57580   507.95008  148.6726
..            ...         ...        ...         ...       ...
128       VSS-UCS    0.719160   24.63120   182.68140   21.1785
129      VSV-AZG4   13.807872    8.21040   320.54770  159.0531
130  VSV-AZS4E42A   34.519680    0.00000  1304.83782  545.7260
131      VSV-IFM4   10.088524  100.85108   257.12236   73.0089
132     VSV-IFP4C   11.344288  302.21114   716.15214  152.2124

[133 rows x 5 columns]

#### 绩效汇总表

In [41]:
# 计算退款
refund_table['平台退款费'] = refund_table['Total settlement amount'] * exchange_ratio['USD_CNY']
# 费用透视
refund_table_pivot = refund_table.pivot_table(index='MSKU', values='平台退款费', aggfunc='sum').reset_index()

In [42]:
#### 构建最终的Tik Tok绩效汇总表
tt_all = pd.concat([
    final_orders_pivot['MSKU'],
    advertise_info['MSKU'],
    refund_table_pivot['MSKU']
]).drop_duplicates().dropna().to_frame(name='MSKU')

In [43]:
# 结算单相关
final_orders_pivot_map1 = final_orders_pivot.set_index('MSKU')['结算金额(CNY)'].to_dict()
final_orders_pivot_map2 = final_orders_pivot.set_index('MSKU')['采购成本'].to_dict()
final_orders_pivot_map3 = final_orders_pivot.set_index('MSKU')['头程成本'].to_dict()
final_orders_pivot_map4 = final_orders_pivot.set_index('MSKU')['尾程费用'].to_dict()
# 广告费
advertise_info_map = advertise_info.set_index('MSKU')['花费人民币'].to_dict()
# 退款费
refund_table_pivot_map = refund_table_pivot.set_index('MSKU')['平台退款费'].to_dict()

In [44]:
# 都是USD
other_adjustment = 220.57 # 分摊活动费
storage_fee = 73.31 # 分摊仓储费

In [45]:
tt_all['结算金额'] = tt_all['MSKU'].map(final_orders_pivot_map1).fillna(0)
tt_all['采购成本'] = tt_all['MSKU'].map(final_orders_pivot_map2).fillna(0)
tt_all['头程成本'] = tt_all['MSKU'].map(final_orders_pivot_map3).fillna(0)
tt_all['尾程费用'] = tt_all['MSKU'].map(final_orders_pivot_map4).fillna(0)
tt_all['广告费'] = tt_all['MSKU'].map(advertise_info_map).fillna(0)
# tt_all['平台退款费'] = 0
tt_all['平台退款费'] = tt_all['MSKU'].map(refund_table_pivot_map).fillna(0)
tt_all['结算金额占比'] = tt_all['结算金额'] / tt_all['结算金额'].sum()
tt_all['活动费分摊'] = other_adjustment * exchange_ratio['USD_CNY'] * tt_all['结算金额占比']
tt_all['仓储费分摊'] = storage_fee * exchange_ratio['USD_CNY'] * tt_all['结算金额占比']
tt_all['利润'] = tt_all['结算金额'] - tt_all['采购成本'] - tt_all['头程成本']  - tt_all['尾程费用'] - tt_all['广告费'] + tt_all['平台退款费'] - tt_all['活动费分摊'] - tt_all['仓储费分摊']

In [46]:
tt_all.to_excel(rf'Tik Tok\{last_month_str}\{cal_month}月Tik Tok绩效汇总表.xlsx', index=False)

##### 中间表输出

In [47]:
with pd.ExcelWriter(rf'Tik Tok\{last_month_str}\{cal_month}月中间表.xlsx') as writer:
    final_orders.to_excel(writer, sheet_name='结算单处理', index=False)
    refund_table.to_excel(writer, sheet_name='退款单处理', index=False)
    cancelled_output_df.to_excel(writer, sheet_name='取消订单', index=False)